namespace WebApiFormApp
{
    partial class LoginRegisterForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(LoginRegisterForm));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            pnlReg = new Panel();
            bunifuShadowPanel2 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            label2 = new Label();
            txtRegFirstName = new Bunifu.UI.WinForms.BunifuTextBox();
            txtRegLastName = new Bunifu.UI.WinForms.BunifuTextBox();
            btnToLogin = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            txtRegEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            btnRegister = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            txtRegPw = new Bunifu.UI.WinForms.BunifuTextBox();
            txtRegUserName = new Bunifu.UI.WinForms.BunifuTextBox();
            pnlLogin = new Panel();
            bunifuShadowPanel1 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            label1 = new Label();
            txtEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            btnToReg = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            txtPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            btnLogin = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            pnlReg.SuspendLayout();
            bunifuShadowPanel2.SuspendLayout();
            pnlLogin.SuspendLayout();
            bunifuShadowPanel1.SuspendLayout();
            SuspendLayout();
            // 
            // pnlReg
            // 
            pnlReg.BackColor = Color.FromArgb(34, 35, 39);
            pnlReg.Controls.Add(bunifuShadowPanel2);
            pnlReg.Dock = DockStyle.Fill;
            pnlReg.Location = new Point(0, 0);
            pnlReg.Name = "pnlReg";
            pnlReg.Size = new Size(800, 450);
            pnlReg.TabIndex = 28;
            pnlReg.Visible = false;
            // 
            // bunifuShadowPanel2
            // 
            bunifuShadowPanel2.Anchor = AnchorStyles.Top;
            bunifuShadowPanel2.BackColor = Color.Transparent;
            bunifuShadowPanel2.BorderColor = Color.FromArgb(134, 135, 140);
            bunifuShadowPanel2.BorderRadius = 1;
            bunifuShadowPanel2.BorderThickness = 1;
            bunifuShadowPanel2.Controls.Add(label2);
            bunifuShadowPanel2.Controls.Add(txtRegFirstName);
            bunifuShadowPanel2.Controls.Add(txtRegLastName);
            bunifuShadowPanel2.Controls.Add(btnToLogin);
            bunifuShadowPanel2.Controls.Add(txtRegEmail);
            bunifuShadowPanel2.Controls.Add(btnRegister);
            bunifuShadowPanel2.Controls.Add(txtRegPw);
            bunifuShadowPanel2.Controls.Add(txtRegUserName);
            bunifuShadowPanel2.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            bunifuShadowPanel2.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            bunifuShadowPanel2.Location = new Point(250, 50);
            bunifuShadowPanel2.Name = "bunifuShadowPanel2";
            bunifuShadowPanel2.PanelColor = Color.FromArgb(58, 57, 63);
            bunifuShadowPanel2.PanelColor2 = Color.FromArgb(58, 57, 63);
            bunifuShadowPanel2.ShadowColor = SystemColors.ControlText;
            bunifuShadowPanel2.ShadowDept = 2;
            bunifuShadowPanel2.ShadowDepth = 3;
            bunifuShadowPanel2.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Dropped;
            bunifuShadowPanel2.ShadowTopLeftVisible = false;
            bunifuShadowPanel2.Size = new Size(300, 335);
            bunifuShadowPanel2.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            bunifuShadowPanel2.TabIndex = 22;
            // 
            // label2
            // 
            label2.AutoSize = true;
            label2.Font = new Font("Segoe UI", 19F, FontStyle.Bold);
            label2.ForeColor = SystemColors.ControlLight;
            label2.Location = new Point(95, 15);
            label2.Name = "label2";
            label2.Size = new Size(111, 36);
            label2.TabIndex = 6;
            label2.Text = "Sign Up";
            label2.TextAlign = ContentAlignment.MiddleCenter;
            // 
            // txtRegFirstName
            // 
            txtRegFirstName.AcceptsReturn = false;
            txtRegFirstName.AcceptsTab = false;
            txtRegFirstName.Anchor = AnchorStyles.Top;
            txtRegFirstName.AnimationSpeed = 200;
            txtRegFirstName.AutoCompleteMode = AutoCompleteMode.None;
            txtRegFirstName.AutoCompleteSource = AutoCompleteSource.None;
            txtRegFirstName.AutoSizeHeight = true;
            txtRegFirstName.BackColor = Color.Transparent;
            txtRegFirstName.BackgroundImage = (Image)resources.GetObject("txtRegFirstName.BackgroundImage");
            txtRegFirstName.BorderColorActive = SystemColors.MenuHighlight;
            txtRegFirstName.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtRegFirstName.BorderColorHover = SystemColors.MenuHighlight;
            txtRegFirstName.BorderColorIdle = Color.Silver;
            txtRegFirstName.BorderRadius = 30;
            txtRegFirstName.BorderThickness = 3;
            txtRegFirstName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtRegFirstName.CharacterCasing = CharacterCasing.Normal;
            txtRegFirstName.DefaultFont = new Font("Segoe UI", 9.25F);
            txtRegFirstName.DefaultText = "";
            txtRegFirstName.FillColor = Color.White;
            txtRegFirstName.HideSelection = true;
            txtRegFirstName.IconLeft = null;
            txtRegFirstName.IconLeftCursor = Cursors.IBeam;
            txtRegFirstName.IconPadding = 10;
            txtRegFirstName.IconRight = null;
            txtRegFirstName.IconRightCursor = Cursors.IBeam;
            txtRegFirstName.Location = new Point(20, 64);
            txtRegFirstName.MaxLength = 32767;
            txtRegFirstName.MinimumSize = new Size(1, 1);
            txtRegFirstName.Modified = false;
            txtRegFirstName.Multiline = false;
            txtRegFirstName.Name = "txtRegFirstName";
            stateProperties1.BorderColor = SystemColors.MenuHighlight;
            stateProperties1.FillColor = Color.Empty;
            stateProperties1.ForeColor = Color.Empty;
            stateProperties1.PlaceholderForeColor = Color.Empty;
            txtRegFirstName.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties2.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties2.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties2.PlaceholderForeColor = Color.DarkGray;
            txtRegFirstName.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = SystemColors.MenuHighlight;
            stateProperties3.FillColor = Color.Empty;
            stateProperties3.ForeColor = Color.Empty;
            stateProperties3.PlaceholderForeColor = Color.Empty;
            txtRegFirstName.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = Color.Silver;
            stateProperties4.FillColor = Color.White;
            stateProperties4.ForeColor = Color.Empty;
            stateProperties4.PlaceholderForeColor = Color.Empty;
            txtRegFirstName.OnIdleState = stateProperties4;
            txtRegFirstName.Padding = new Padding(3);
            txtRegFirstName.PasswordChar = '\0';
            txtRegFirstName.PlaceholderForeColor = Color.Silver;
            txtRegFirstName.PlaceholderText = "First Name";
            txtRegFirstName.ReadOnly = false;
            txtRegFirstName.ScrollBars = ScrollBars.None;
            txtRegFirstName.SelectedText = "";
            txtRegFirstName.SelectionLength = 0;
            txtRegFirstName.SelectionStart = 0;
            txtRegFirstName.ShortcutsEnabled = true;
            txtRegFirstName.Size = new Size(260, 39);
            txtRegFirstName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtRegFirstName.TabIndex = 5;
            txtRegFirstName.TextAlign = HorizontalAlignment.Left;
            txtRegFirstName.TextMarginBottom = 0;
            txtRegFirstName.TextMarginLeft = 3;
            txtRegFirstName.TextMarginTop = 1;
            txtRegFirstName.TextPlaceholder = "First Name";
            txtRegFirstName.UseSystemPasswordChar = false;
            txtRegFirstName.WordWrap = true;
            // 
            // txtRegLastName
            // 
            txtRegLastName.AcceptsReturn = false;
            txtRegLastName.AcceptsTab = false;
            txtRegLastName.Anchor = AnchorStyles.Top;
            txtRegLastName.AnimationSpeed = 200;
            txtRegLastName.AutoCompleteMode = AutoCompleteMode.None;
            txtRegLastName.AutoCompleteSource = AutoCompleteSource.None;
            txtRegLastName.AutoSizeHeight = true;
            txtRegLastName.BackColor = Color.Transparent;
            txtRegLastName.BackgroundImage = (Image)resources.GetObject("txtRegLastName.BackgroundImage");
            txtRegLastName.BorderColorActive = SystemColors.MenuHighlight;
            txtRegLastName.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtRegLastName.BorderColorHover = SystemColors.MenuHighlight;
            txtRegLastName.BorderColorIdle = Color.Silver;
            txtRegLastName.BorderRadius = 30;
            txtRegLastName.BorderThickness = 3;
            txtRegLastName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtRegLastName.CharacterCasing = CharacterCasing.Normal;
            txtRegLastName.DefaultFont = new Font("Segoe UI", 9.25F);
            txtRegLastName.DefaultText = "";
            txtRegLastName.FillColor = Color.White;
            txtRegLastName.HideSelection = true;
            txtRegLastName.IconLeft = null;
            txtRegLastName.IconLeftCursor = Cursors.IBeam;
            txtRegLastName.IconPadding = 10;
            txtRegLastName.IconRight = null;
            txtRegLastName.IconRightCursor = Cursors.IBeam;
            txtRegLastName.Location = new Point(20, 104);
            txtRegLastName.MaxLength = 32767;
            txtRegLastName.MinimumSize = new Size(1, 1);
            txtRegLastName.Modified = false;
            txtRegLastName.Multiline = false;
            txtRegLastName.Name = "txtRegLastName";
            stateProperties5.BorderColor = SystemColors.MenuHighlight;
            stateProperties5.FillColor = Color.Empty;
            stateProperties5.ForeColor = Color.Empty;
            stateProperties5.PlaceholderForeColor = Color.Empty;
            txtRegLastName.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties6.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties6.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties6.PlaceholderForeColor = Color.DarkGray;
            txtRegLastName.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = SystemColors.MenuHighlight;
            stateProperties7.FillColor = Color.Empty;
            stateProperties7.ForeColor = Color.Empty;
            stateProperties7.PlaceholderForeColor = Color.Empty;
            txtRegLastName.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = Color.Silver;
            stateProperties8.FillColor = Color.White;
            stateProperties8.ForeColor = Color.Empty;
            stateProperties8.PlaceholderForeColor = Color.Empty;
            txtRegLastName.OnIdleState = stateProperties8;
            txtRegLastName.Padding = new Padding(3);
            txtRegLastName.PasswordChar = '\0';
            txtRegLastName.PlaceholderForeColor = Color.Silver;
            txtRegLastName.PlaceholderText = "Last Name";
            txtRegLastName.ReadOnly = false;
            txtRegLastName.ScrollBars = ScrollBars.None;
            txtRegLastName.SelectedText = "";
            txtRegLastName.SelectionLength = 0;
            txtRegLastName.SelectionStart = 0;
            txtRegLastName.ShortcutsEnabled = true;
            txtRegLastName.Size = new Size(260, 39);
            txtRegLastName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtRegLastName.TabIndex = 6;
            txtRegLastName.TextAlign = HorizontalAlignment.Left;
            txtRegLastName.TextMarginBottom = 0;
            txtRegLastName.TextMarginLeft = 3;
            txtRegLastName.TextMarginTop = 1;
            txtRegLastName.TextPlaceholder = "Last Name";
            txtRegLastName.UseSystemPasswordChar = false;
            txtRegLastName.WordWrap = true;
            // 
            // btnToLogin
            // 
            btnToLogin.AllowAnimations = true;
            btnToLogin.AllowMouseEffects = true;
            btnToLogin.AllowToggling = false;
            btnToLogin.Anchor = AnchorStyles.Top;
            btnToLogin.AnimationSpeed = 200;
            btnToLogin.AutoGenerateColors = false;
            btnToLogin.AutoRoundBorders = false;
            btnToLogin.AutoSizeLeftIcon = true;
            btnToLogin.AutoSizeRightIcon = true;
            btnToLogin.BackColor = Color.Transparent;
            btnToLogin.BackColor1 = Color.FromArgb(51, 122, 183);
            btnToLogin.BackgroundImage = (Image)resources.GetObject("btnToLogin.BackgroundImage");
            btnToLogin.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnToLogin.ButtonText = "Login";
            btnToLogin.ButtonTextMarginLeft = 0;
            btnToLogin.ColorContrastOnClick = 45;
            btnToLogin.ColorContrastOnHover = 45;
            btnToLogin.Cursor = Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            btnToLogin.CustomizableEdges = borderEdges1;
            btnToLogin.DialogResult = DialogResult.None;
            btnToLogin.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnToLogin.DisabledFillColor = Color.Empty;
            btnToLogin.DisabledForecolor = Color.Empty;
            btnToLogin.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            btnToLogin.Font = new Font("Segoe UI", 10F, FontStyle.Underline);
            btnToLogin.ForeColor = SystemColors.MenuHighlight;
            btnToLogin.IconLeft = null;
            btnToLogin.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnToLogin.IconLeftCursor = Cursors.Default;
            btnToLogin.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnToLogin.IconMarginLeft = 11;
            btnToLogin.IconPadding = 10;
            btnToLogin.IconRight = null;
            btnToLogin.IconRightAlign = ContentAlignment.MiddleRight;
            btnToLogin.IconRightCursor = Cursors.Default;
            btnToLogin.IconRightPadding = new Padding(3, 3, 7, 3);
            btnToLogin.IconSize = 25;
            btnToLogin.IdleBorderColor = Color.Empty;
            btnToLogin.IdleBorderRadius = 0;
            btnToLogin.IdleBorderThickness = 0;
            btnToLogin.IdleFillColor = Color.Empty;
            btnToLogin.IdleIconLeftImage = null;
            btnToLogin.IdleIconRightImage = null;
            btnToLogin.IndicateFocus = false;
            btnToLogin.Location = new Point(190, 282);
            btnToLogin.Name = "btnToLogin";
            btnToLogin.OnDisabledState.BorderColor = Color.Transparent;
            btnToLogin.OnDisabledState.BorderRadius = 1;
            btnToLogin.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnToLogin.OnDisabledState.BorderThickness = 0;
            btnToLogin.OnDisabledState.FillColor = Color.Transparent;
            btnToLogin.OnDisabledState.ForeColor = SystemColors.MenuHighlight;
            btnToLogin.OnDisabledState.IconLeftImage = null;
            btnToLogin.OnDisabledState.IconRightImage = null;
            btnToLogin.onHoverState.BorderColor = Color.Transparent;
            btnToLogin.onHoverState.BorderRadius = 1;
            btnToLogin.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnToLogin.onHoverState.BorderThickness = 0;
            btnToLogin.onHoverState.FillColor = Color.Transparent;
            btnToLogin.onHoverState.ForeColor = SystemColors.MenuHighlight;
            btnToLogin.onHoverState.IconLeftImage = null;
            btnToLogin.onHoverState.IconRightImage = null;
            btnToLogin.OnIdleState.BorderColor = Color.Transparent;
            btnToLogin.OnIdleState.BorderRadius = 1;
            btnToLogin.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnToLogin.OnIdleState.BorderThickness = 0;
            btnToLogin.OnIdleState.FillColor = Color.Transparent;
            btnToLogin.OnIdleState.ForeColor = SystemColors.MenuHighlight;
            btnToLogin.OnIdleState.IconLeftImage = null;
            btnToLogin.OnIdleState.IconRightImage = null;
            btnToLogin.OnPressedState.BorderColor = Color.Transparent;
            btnToLogin.OnPressedState.BorderRadius = 1;
            btnToLogin.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnToLogin.OnPressedState.BorderThickness = 0;
            btnToLogin.OnPressedState.FillColor = Color.Transparent;
            btnToLogin.OnPressedState.ForeColor = SystemColors.MenuHighlight;
            btnToLogin.OnPressedState.IconLeftImage = null;
            btnToLogin.OnPressedState.IconRightImage = null;
            btnToLogin.Size = new Size(60, 20);
            btnToLogin.TabIndex = 21;
            btnToLogin.TextAlign = ContentAlignment.MiddleCenter;
            btnToLogin.TextAlignment = HorizontalAlignment.Center;
            btnToLogin.TextMarginLeft = 0;
            btnToLogin.TextPadding = new Padding(0);
            btnToLogin.UseDefaultRadiusAndThickness = true;
            btnToLogin.Click += btnToLogin_Click;
            // 
            // txtRegEmail
            // 
            txtRegEmail.AcceptsReturn = false;
            txtRegEmail.AcceptsTab = false;
            txtRegEmail.Anchor = AnchorStyles.Top;
            txtRegEmail.AnimationSpeed = 200;
            txtRegEmail.AutoCompleteMode = AutoCompleteMode.None;
            txtRegEmail.AutoCompleteSource = AutoCompleteSource.None;
            txtRegEmail.AutoSizeHeight = true;
            txtRegEmail.BackColor = Color.Transparent;
            txtRegEmail.BackgroundImage = (Image)resources.GetObject("txtRegEmail.BackgroundImage");
            txtRegEmail.BorderColorActive = SystemColors.MenuHighlight;
            txtRegEmail.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtRegEmail.BorderColorHover = SystemColors.MenuHighlight;
            txtRegEmail.BorderColorIdle = Color.Silver;
            txtRegEmail.BorderRadius = 30;
            txtRegEmail.BorderThickness = 3;
            txtRegEmail.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtRegEmail.CharacterCasing = CharacterCasing.Normal;
            txtRegEmail.DefaultFont = new Font("Segoe UI", 9.25F);
            txtRegEmail.DefaultText = "";
            txtRegEmail.FillColor = Color.White;
            txtRegEmail.HideSelection = true;
            txtRegEmail.IconLeft = null;
            txtRegEmail.IconLeftCursor = Cursors.IBeam;
            txtRegEmail.IconPadding = 10;
            txtRegEmail.IconRight = null;
            txtRegEmail.IconRightCursor = Cursors.IBeam;
            txtRegEmail.Location = new Point(20, 184);
            txtRegEmail.MaxLength = 32767;
            txtRegEmail.MinimumSize = new Size(1, 1);
            txtRegEmail.Modified = false;
            txtRegEmail.Multiline = false;
            txtRegEmail.Name = "txtRegEmail";
            stateProperties9.BorderColor = SystemColors.MenuHighlight;
            stateProperties9.FillColor = Color.Empty;
            stateProperties9.ForeColor = Color.Empty;
            stateProperties9.PlaceholderForeColor = Color.Empty;
            txtRegEmail.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties10.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties10.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties10.PlaceholderForeColor = Color.DarkGray;
            txtRegEmail.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = SystemColors.MenuHighlight;
            stateProperties11.FillColor = Color.Empty;
            stateProperties11.ForeColor = Color.Empty;
            stateProperties11.PlaceholderForeColor = Color.Empty;
            txtRegEmail.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = Color.Silver;
            stateProperties12.FillColor = Color.White;
            stateProperties12.ForeColor = Color.Empty;
            stateProperties12.PlaceholderForeColor = Color.Empty;
            txtRegEmail.OnIdleState = stateProperties12;
            txtRegEmail.Padding = new Padding(3);
            txtRegEmail.PasswordChar = '\0';
            txtRegEmail.PlaceholderForeColor = Color.Silver;
            txtRegEmail.PlaceholderText = "Email";
            txtRegEmail.ReadOnly = false;
            txtRegEmail.ScrollBars = ScrollBars.None;
            txtRegEmail.SelectedText = "";
            txtRegEmail.SelectionLength = 0;
            txtRegEmail.SelectionStart = 0;
            txtRegEmail.ShortcutsEnabled = true;
            txtRegEmail.Size = new Size(260, 39);
            txtRegEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtRegEmail.TabIndex = 8;
            txtRegEmail.TextAlign = HorizontalAlignment.Left;
            txtRegEmail.TextMarginBottom = 0;
            txtRegEmail.TextMarginLeft = 3;
            txtRegEmail.TextMarginTop = 1;
            txtRegEmail.TextPlaceholder = "Email";
            txtRegEmail.UseSystemPasswordChar = false;
            txtRegEmail.WordWrap = true;
            // 
            // btnRegister
            // 
            btnRegister.AllowAnimations = true;
            btnRegister.AllowMouseEffects = true;
            btnRegister.AllowToggling = false;
            btnRegister.Anchor = AnchorStyles.Top;
            btnRegister.AnimationSpeed = 200;
            btnRegister.AutoGenerateColors = false;
            btnRegister.AutoRoundBorders = false;
            btnRegister.AutoSizeLeftIcon = true;
            btnRegister.AutoSizeRightIcon = true;
            btnRegister.BackColor = Color.Transparent;
            btnRegister.BackColor1 = Color.FromArgb(51, 122, 183);
            btnRegister.BackgroundImage = (Image)resources.GetObject("btnRegister.BackgroundImage");
            btnRegister.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnRegister.ButtonText = "Register";
            btnRegister.ButtonTextMarginLeft = 0;
            btnRegister.ColorContrastOnClick = 45;
            btnRegister.ColorContrastOnHover = 45;
            btnRegister.Cursor = Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            btnRegister.CustomizableEdges = borderEdges2;
            btnRegister.DialogResult = DialogResult.None;
            btnRegister.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnRegister.DisabledFillColor = Color.Empty;
            btnRegister.DisabledForecolor = Color.Empty;
            btnRegister.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnRegister.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 162);
            btnRegister.ForeColor = Color.White;
            btnRegister.IconLeft = null;
            btnRegister.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnRegister.IconLeftCursor = Cursors.Default;
            btnRegister.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnRegister.IconMarginLeft = 11;
            btnRegister.IconPadding = 10;
            btnRegister.IconRight = null;
            btnRegister.IconRightAlign = ContentAlignment.MiddleRight;
            btnRegister.IconRightCursor = Cursors.Default;
            btnRegister.IconRightPadding = new Padding(3, 3, 7, 3);
            btnRegister.IconSize = 25;
            btnRegister.IdleBorderColor = Color.Empty;
            btnRegister.IdleBorderRadius = 0;
            btnRegister.IdleBorderThickness = 0;
            btnRegister.IdleFillColor = Color.Empty;
            btnRegister.IdleIconLeftImage = null;
            btnRegister.IdleIconRightImage = null;
            btnRegister.IndicateFocus = false;
            btnRegister.Location = new Point(50, 274);
            btnRegister.Name = "btnRegister";
            btnRegister.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnRegister.OnDisabledState.BorderRadius = 25;
            btnRegister.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnRegister.OnDisabledState.BorderThickness = 0;
            btnRegister.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnRegister.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnRegister.OnDisabledState.IconLeftImage = null;
            btnRegister.OnDisabledState.IconRightImage = null;
            btnRegister.onHoverState.BorderColor = Color.Blue;
            btnRegister.onHoverState.BorderRadius = 25;
            btnRegister.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnRegister.onHoverState.BorderThickness = 0;
            btnRegister.onHoverState.FillColor = Color.Blue;
            btnRegister.onHoverState.ForeColor = Color.White;
            btnRegister.onHoverState.IconLeftImage = null;
            btnRegister.onHoverState.IconRightImage = null;
            btnRegister.OnIdleState.BorderColor = Color.RoyalBlue;
            btnRegister.OnIdleState.BorderRadius = 25;
            btnRegister.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnRegister.OnIdleState.BorderThickness = 0;
            btnRegister.OnIdleState.FillColor = Color.RoyalBlue;
            btnRegister.OnIdleState.ForeColor = Color.White;
            btnRegister.OnIdleState.IconLeftImage = null;
            btnRegister.OnIdleState.IconRightImage = null;
            btnRegister.OnPressedState.BorderColor = Color.MediumBlue;
            btnRegister.OnPressedState.BorderRadius = 25;
            btnRegister.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnRegister.OnPressedState.BorderThickness = 0;
            btnRegister.OnPressedState.FillColor = Color.MediumBlue;
            btnRegister.OnPressedState.ForeColor = Color.White;
            btnRegister.OnPressedState.IconLeftImage = null;
            btnRegister.OnPressedState.IconRightImage = null;
            btnRegister.Size = new Size(137, 35);
            btnRegister.TabIndex = 20;
            btnRegister.TextAlign = ContentAlignment.MiddleCenter;
            btnRegister.TextAlignment = HorizontalAlignment.Center;
            btnRegister.TextMarginLeft = 0;
            btnRegister.TextPadding = new Padding(0);
            btnRegister.UseDefaultRadiusAndThickness = true;
            btnRegister.Click += btnRegister_Click;
            // 
            // txtRegPw
            // 
            txtRegPw.AcceptsReturn = false;
            txtRegPw.AcceptsTab = false;
            txtRegPw.Anchor = AnchorStyles.Top;
            txtRegPw.AnimationSpeed = 200;
            txtRegPw.AutoCompleteMode = AutoCompleteMode.None;
            txtRegPw.AutoCompleteSource = AutoCompleteSource.None;
            txtRegPw.AutoSizeHeight = true;
            txtRegPw.BackColor = Color.Transparent;
            txtRegPw.BackgroundImage = (Image)resources.GetObject("txtRegPw.BackgroundImage");
            txtRegPw.BorderColorActive = SystemColors.MenuHighlight;
            txtRegPw.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtRegPw.BorderColorHover = SystemColors.MenuHighlight;
            txtRegPw.BorderColorIdle = Color.Silver;
            txtRegPw.BorderRadius = 30;
            txtRegPw.BorderThickness = 3;
            txtRegPw.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtRegPw.CharacterCasing = CharacterCasing.Normal;
            txtRegPw.DefaultFont = new Font("Segoe UI", 9.25F);
            txtRegPw.DefaultText = "";
            txtRegPw.FillColor = Color.White;
            txtRegPw.HideSelection = true;
            txtRegPw.IconLeft = null;
            txtRegPw.IconLeftCursor = Cursors.IBeam;
            txtRegPw.IconPadding = 10;
            txtRegPw.IconRight = null;
            txtRegPw.IconRightCursor = Cursors.IBeam;
            txtRegPw.Location = new Point(20, 224);
            txtRegPw.MaxLength = 32767;
            txtRegPw.MinimumSize = new Size(1, 1);
            txtRegPw.Modified = false;
            txtRegPw.Multiline = false;
            txtRegPw.Name = "txtRegPw";
            stateProperties13.BorderColor = SystemColors.MenuHighlight;
            stateProperties13.FillColor = Color.Empty;
            stateProperties13.ForeColor = Color.Empty;
            stateProperties13.PlaceholderForeColor = Color.Empty;
            txtRegPw.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties14.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties14.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties14.PlaceholderForeColor = Color.DarkGray;
            txtRegPw.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = SystemColors.MenuHighlight;
            stateProperties15.FillColor = Color.Empty;
            stateProperties15.ForeColor = Color.Empty;
            stateProperties15.PlaceholderForeColor = Color.Empty;
            txtRegPw.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = Color.Silver;
            stateProperties16.FillColor = Color.White;
            stateProperties16.ForeColor = Color.Empty;
            stateProperties16.PlaceholderForeColor = Color.Empty;
            txtRegPw.OnIdleState = stateProperties16;
            txtRegPw.Padding = new Padding(3);
            txtRegPw.PasswordChar = '\0';
            txtRegPw.PlaceholderForeColor = Color.Silver;
            txtRegPw.PlaceholderText = "Password";
            txtRegPw.ReadOnly = false;
            txtRegPw.ScrollBars = ScrollBars.None;
            txtRegPw.SelectedText = "";
            txtRegPw.SelectionLength = 0;
            txtRegPw.SelectionStart = 0;
            txtRegPw.ShortcutsEnabled = true;
            txtRegPw.Size = new Size(260, 39);
            txtRegPw.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtRegPw.TabIndex = 9;
            txtRegPw.TextAlign = HorizontalAlignment.Left;
            txtRegPw.TextMarginBottom = 0;
            txtRegPw.TextMarginLeft = 3;
            txtRegPw.TextMarginTop = 1;
            txtRegPw.TextPlaceholder = "Password";
            txtRegPw.UseSystemPasswordChar = false;
            txtRegPw.WordWrap = true;
            // 
            // txtRegUserName
            // 
            txtRegUserName.AcceptsReturn = false;
            txtRegUserName.AcceptsTab = false;
            txtRegUserName.Anchor = AnchorStyles.Top;
            txtRegUserName.AnimationSpeed = 200;
            txtRegUserName.AutoCompleteMode = AutoCompleteMode.None;
            txtRegUserName.AutoCompleteSource = AutoCompleteSource.None;
            txtRegUserName.AutoSizeHeight = true;
            txtRegUserName.BackColor = Color.Transparent;
            txtRegUserName.BackgroundImage = (Image)resources.GetObject("txtRegUserName.BackgroundImage");
            txtRegUserName.BorderColorActive = SystemColors.MenuHighlight;
            txtRegUserName.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtRegUserName.BorderColorHover = SystemColors.MenuHighlight;
            txtRegUserName.BorderColorIdle = Color.Silver;
            txtRegUserName.BorderRadius = 30;
            txtRegUserName.BorderThickness = 3;
            txtRegUserName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtRegUserName.CharacterCasing = CharacterCasing.Normal;
            txtRegUserName.DefaultFont = new Font("Segoe UI", 9.25F);
            txtRegUserName.DefaultText = "";
            txtRegUserName.FillColor = Color.White;
            txtRegUserName.HideSelection = true;
            txtRegUserName.IconLeft = null;
            txtRegUserName.IconLeftCursor = Cursors.IBeam;
            txtRegUserName.IconPadding = 10;
            txtRegUserName.IconRight = null;
            txtRegUserName.IconRightCursor = Cursors.IBeam;
            txtRegUserName.Location = new Point(20, 144);
            txtRegUserName.MaxLength = 32767;
            txtRegUserName.MinimumSize = new Size(1, 1);
            txtRegUserName.Modified = false;
            txtRegUserName.Multiline = false;
            txtRegUserName.Name = "txtRegUserName";
            stateProperties17.BorderColor = SystemColors.MenuHighlight;
            stateProperties17.FillColor = Color.Empty;
            stateProperties17.ForeColor = Color.Empty;
            stateProperties17.PlaceholderForeColor = Color.Empty;
            txtRegUserName.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties18.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties18.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties18.PlaceholderForeColor = Color.DarkGray;
            txtRegUserName.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = SystemColors.MenuHighlight;
            stateProperties19.FillColor = Color.Empty;
            stateProperties19.ForeColor = Color.Empty;
            stateProperties19.PlaceholderForeColor = Color.Empty;
            txtRegUserName.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = Color.Silver;
            stateProperties20.FillColor = Color.White;
            stateProperties20.ForeColor = Color.Empty;
            stateProperties20.PlaceholderForeColor = Color.Empty;
            txtRegUserName.OnIdleState = stateProperties20;
            txtRegUserName.Padding = new Padding(3);
            txtRegUserName.PasswordChar = '\0';
            txtRegUserName.PlaceholderForeColor = Color.Silver;
            txtRegUserName.PlaceholderText = "Username";
            txtRegUserName.ReadOnly = false;
            txtRegUserName.ScrollBars = ScrollBars.None;
            txtRegUserName.SelectedText = "";
            txtRegUserName.SelectionLength = 0;
            txtRegUserName.SelectionStart = 0;
            txtRegUserName.ShortcutsEnabled = true;
            txtRegUserName.Size = new Size(260, 39);
            txtRegUserName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtRegUserName.TabIndex = 7;
            txtRegUserName.TextAlign = HorizontalAlignment.Left;
            txtRegUserName.TextMarginBottom = 0;
            txtRegUserName.TextMarginLeft = 3;
            txtRegUserName.TextMarginTop = 1;
            txtRegUserName.TextPlaceholder = "Username";
            txtRegUserName.UseSystemPasswordChar = false;
            txtRegUserName.WordWrap = true;
            // 
            // pnlLogin
            // 
            pnlLogin.BackColor = Color.FromArgb(34, 35, 39);
            pnlLogin.Controls.Add(bunifuShadowPanel1);
            pnlLogin.Dock = DockStyle.Fill;
            pnlLogin.Location = new Point(0, 0);
            pnlLogin.Name = "pnlLogin";
            pnlLogin.Size = new Size(800, 450);
            pnlLogin.TabIndex = 27;
            // 
            // bunifuShadowPanel1
            // 
            bunifuShadowPanel1.Anchor = AnchorStyles.Top;
            bunifuShadowPanel1.BackColor = Color.Transparent;
            bunifuShadowPanel1.BorderColor = Color.FromArgb(134, 135, 140);
            bunifuShadowPanel1.BorderRadius = 1;
            bunifuShadowPanel1.BorderThickness = 1;
            bunifuShadowPanel1.Controls.Add(label1);
            bunifuShadowPanel1.Controls.Add(txtEmail);
            bunifuShadowPanel1.Controls.Add(btnToReg);
            bunifuShadowPanel1.Controls.Add(txtPassword);
            bunifuShadowPanel1.Controls.Add(btnLogin);
            bunifuShadowPanel1.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            bunifuShadowPanel1.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            bunifuShadowPanel1.Location = new Point(250, 100);
            bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            bunifuShadowPanel1.PanelColor = Color.FromArgb(58, 57, 63);
            bunifuShadowPanel1.PanelColor2 = Color.FromArgb(58, 57, 63);
            bunifuShadowPanel1.ShadowColor = SystemColors.ControlText;
            bunifuShadowPanel1.ShadowDept = 2;
            bunifuShadowPanel1.ShadowDepth = 3;
            bunifuShadowPanel1.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Dropped;
            bunifuShadowPanel1.ShadowTopLeftVisible = false;
            bunifuShadowPanel1.Size = new Size(300, 235);
            bunifuShadowPanel1.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            bunifuShadowPanel1.TabIndex = 6;
            // 
            // label1
            // 
            label1.AutoSize = true;
            label1.Font = new Font("Segoe UI", 19F, FontStyle.Bold);
            label1.ForeColor = SystemColors.ControlLight;
            label1.Location = new Point(100, 15);
            label1.Name = "label1";
            label1.Size = new Size(100, 36);
            label1.TabIndex = 6;
            label1.Text = "Sign In";
            label1.TextAlign = ContentAlignment.MiddleCenter;
            // 
            // txtEmail
            // 
            txtEmail.AcceptsReturn = false;
            txtEmail.AcceptsTab = false;
            txtEmail.Anchor = AnchorStyles.Top;
            txtEmail.AnimationSpeed = 200;
            txtEmail.AutoCompleteMode = AutoCompleteMode.None;
            txtEmail.AutoCompleteSource = AutoCompleteSource.None;
            txtEmail.AutoSizeHeight = true;
            txtEmail.BackColor = Color.Transparent;
            txtEmail.BackgroundImage = (Image)resources.GetObject("txtEmail.BackgroundImage");
            txtEmail.BorderColorActive = SystemColors.MenuHighlight;
            txtEmail.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtEmail.BorderColorHover = SystemColors.MenuHighlight;
            txtEmail.BorderColorIdle = Color.Silver;
            txtEmail.BorderRadius = 30;
            txtEmail.BorderThickness = 3;
            txtEmail.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtEmail.CharacterCasing = CharacterCasing.Normal;
            txtEmail.DefaultFont = new Font("Segoe UI", 9.25F);
            txtEmail.DefaultText = "admin@system.com";
            txtEmail.FillColor = Color.White;
            txtEmail.HideSelection = true;
            txtEmail.IconLeft = null;
            txtEmail.IconLeftCursor = Cursors.IBeam;
            txtEmail.IconPadding = 10;
            txtEmail.IconRight = null;
            txtEmail.IconRightCursor = Cursors.IBeam;
            txtEmail.Lines = new string[]
    {
    "admin@system.com"
    };
            txtEmail.Location = new Point(20, 68);
            txtEmail.MaxLength = 32767;
            txtEmail.MinimumSize = new Size(1, 1);
            txtEmail.Modified = false;
            txtEmail.Multiline = false;
            txtEmail.Name = "txtEmail";
            stateProperties21.BorderColor = SystemColors.MenuHighlight;
            stateProperties21.FillColor = Color.Empty;
            stateProperties21.ForeColor = Color.Empty;
            stateProperties21.PlaceholderForeColor = Color.Empty;
            txtEmail.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties22.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties22.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties22.PlaceholderForeColor = Color.DarkGray;
            txtEmail.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = SystemColors.MenuHighlight;
            stateProperties23.FillColor = Color.Empty;
            stateProperties23.ForeColor = Color.Empty;
            stateProperties23.PlaceholderForeColor = Color.Empty;
            txtEmail.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = Color.Silver;
            stateProperties24.FillColor = Color.White;
            stateProperties24.ForeColor = Color.Empty;
            stateProperties24.PlaceholderForeColor = Color.Empty;
            txtEmail.OnIdleState = stateProperties24;
            txtEmail.Padding = new Padding(3);
            txtEmail.PasswordChar = '\0';
            txtEmail.PlaceholderForeColor = Color.Silver;
            txtEmail.PlaceholderText = "Email";
            txtEmail.ReadOnly = false;
            txtEmail.ScrollBars = ScrollBars.None;
            txtEmail.SelectedText = "";
            txtEmail.SelectionLength = 0;
            txtEmail.SelectionStart = 16;
            txtEmail.ShortcutsEnabled = true;
            txtEmail.Size = new Size(260, 39);
            txtEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtEmail.TabIndex = 1;
            txtEmail.TextAlign = HorizontalAlignment.Left;
            txtEmail.TextMarginBottom = 0;
            txtEmail.TextMarginLeft = 3;
            txtEmail.TextMarginTop = 1;
            txtEmail.TextPlaceholder = "Email";
            txtEmail.UseSystemPasswordChar = false;
            txtEmail.WordWrap = true;
            // 
            // btnToReg
            // 
            btnToReg.AllowAnimations = true;
            btnToReg.AllowMouseEffects = true;
            btnToReg.AllowToggling = false;
            btnToReg.Anchor = AnchorStyles.Top;
            btnToReg.AnimationSpeed = 200;
            btnToReg.AutoGenerateColors = false;
            btnToReg.AutoRoundBorders = false;
            btnToReg.AutoSizeLeftIcon = true;
            btnToReg.AutoSizeRightIcon = true;
            btnToReg.BackColor = Color.Transparent;
            btnToReg.BackColor1 = Color.FromArgb(51, 122, 183);
            btnToReg.BackgroundImage = (Image)resources.GetObject("btnToReg.BackgroundImage");
            btnToReg.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnToReg.ButtonText = "Register";
            btnToReg.ButtonTextMarginLeft = 0;
            btnToReg.ColorContrastOnClick = 45;
            btnToReg.ColorContrastOnHover = 45;
            btnToReg.Cursor = Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            btnToReg.CustomizableEdges = borderEdges3;
            btnToReg.DialogResult = DialogResult.None;
            btnToReg.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnToReg.DisabledFillColor = Color.Empty;
            btnToReg.DisabledForecolor = Color.Empty;
            btnToReg.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            btnToReg.Font = new Font("Segoe UI", 10F, FontStyle.Underline);
            btnToReg.ForeColor = SystemColors.MenuHighlight;
            btnToReg.IconLeft = null;
            btnToReg.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnToReg.IconLeftCursor = Cursors.Default;
            btnToReg.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnToReg.IconMarginLeft = 11;
            btnToReg.IconPadding = 10;
            btnToReg.IconRight = null;
            btnToReg.IconRightAlign = ContentAlignment.MiddleRight;
            btnToReg.IconRightCursor = Cursors.Default;
            btnToReg.IconRightPadding = new Padding(3, 3, 7, 3);
            btnToReg.IconSize = 25;
            btnToReg.IdleBorderColor = Color.Empty;
            btnToReg.IdleBorderRadius = 0;
            btnToReg.IdleBorderThickness = 0;
            btnToReg.IdleFillColor = Color.Empty;
            btnToReg.IdleIconLeftImage = null;
            btnToReg.IdleIconRightImage = null;
            btnToReg.IndicateFocus = false;
            btnToReg.Location = new Point(195, 166);
            btnToReg.Name = "btnToReg";
            btnToReg.OnDisabledState.BorderColor = Color.Transparent;
            btnToReg.OnDisabledState.BorderRadius = 1;
            btnToReg.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnToReg.OnDisabledState.BorderThickness = 0;
            btnToReg.OnDisabledState.FillColor = Color.Transparent;
            btnToReg.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnToReg.OnDisabledState.IconLeftImage = null;
            btnToReg.OnDisabledState.IconRightImage = null;
            btnToReg.onHoverState.BorderColor = Color.Transparent;
            btnToReg.onHoverState.BorderRadius = 1;
            btnToReg.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnToReg.onHoverState.BorderThickness = 0;
            btnToReg.onHoverState.FillColor = Color.Transparent;
            btnToReg.onHoverState.ForeColor = SystemColors.MenuHighlight;
            btnToReg.onHoverState.IconLeftImage = null;
            btnToReg.onHoverState.IconRightImage = null;
            btnToReg.OnIdleState.BorderColor = Color.Transparent;
            btnToReg.OnIdleState.BorderRadius = 1;
            btnToReg.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnToReg.OnIdleState.BorderThickness = 0;
            btnToReg.OnIdleState.FillColor = Color.Transparent;
            btnToReg.OnIdleState.ForeColor = SystemColors.MenuHighlight;
            btnToReg.OnIdleState.IconLeftImage = null;
            btnToReg.OnIdleState.IconRightImage = null;
            btnToReg.OnPressedState.BorderColor = Color.Transparent;
            btnToReg.OnPressedState.BorderRadius = 1;
            btnToReg.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnToReg.OnPressedState.BorderThickness = 0;
            btnToReg.OnPressedState.FillColor = Color.Transparent;
            btnToReg.OnPressedState.ForeColor = SystemColors.MenuHighlight;
            btnToReg.OnPressedState.IconLeftImage = null;
            btnToReg.OnPressedState.IconRightImage = null;
            btnToReg.Size = new Size(60, 20);
            btnToReg.TabIndex = 5;
            btnToReg.TextAlign = ContentAlignment.MiddleCenter;
            btnToReg.TextAlignment = HorizontalAlignment.Center;
            btnToReg.TextMarginLeft = 0;
            btnToReg.TextPadding = new Padding(0);
            btnToReg.UseDefaultRadiusAndThickness = true;
            btnToReg.Click += btnToReg_Click;
            // 
            // txtPassword
            // 
            txtPassword.AcceptsReturn = false;
            txtPassword.AcceptsTab = false;
            txtPassword.Anchor = AnchorStyles.Top;
            txtPassword.AnimationSpeed = 200;
            txtPassword.AutoCompleteMode = AutoCompleteMode.None;
            txtPassword.AutoCompleteSource = AutoCompleteSource.None;
            txtPassword.AutoSizeHeight = true;
            txtPassword.BackColor = Color.Transparent;
            txtPassword.BackgroundImage = (Image)resources.GetObject("txtPassword.BackgroundImage");
            txtPassword.BorderColorActive = SystemColors.MenuHighlight;
            txtPassword.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtPassword.BorderColorHover = SystemColors.MenuHighlight;
            txtPassword.BorderColorIdle = Color.Silver;
            txtPassword.BorderRadius = 30;
            txtPassword.BorderThickness = 3;
            txtPassword.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtPassword.CharacterCasing = CharacterCasing.Normal;
            txtPassword.DefaultFont = new Font("Segoe UI", 9.25F);
            txtPassword.DefaultText = "Admin123*";
            txtPassword.FillColor = Color.White;
            txtPassword.HideSelection = true;
            txtPassword.IconLeft = null;
            txtPassword.IconLeftCursor = Cursors.IBeam;
            txtPassword.IconPadding = 10;
            txtPassword.IconRight = null;
            txtPassword.IconRightCursor = Cursors.IBeam;
            txtPassword.Lines = new string[]
    {
    "Admin123*"
    };
            txtPassword.Location = new Point(20, 108);
            txtPassword.MaxLength = 32767;
            txtPassword.MinimumSize = new Size(1, 1);
            txtPassword.Modified = false;
            txtPassword.Multiline = false;
            txtPassword.Name = "txtPassword";
            stateProperties25.BorderColor = SystemColors.MenuHighlight;
            stateProperties25.FillColor = Color.Empty;
            stateProperties25.ForeColor = Color.Empty;
            stateProperties25.PlaceholderForeColor = Color.Empty;
            txtPassword.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties26.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties26.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties26.PlaceholderForeColor = Color.DarkGray;
            txtPassword.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = SystemColors.MenuHighlight;
            stateProperties27.FillColor = Color.Empty;
            stateProperties27.ForeColor = Color.Empty;
            stateProperties27.PlaceholderForeColor = Color.Empty;
            txtPassword.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = Color.Silver;
            stateProperties28.FillColor = Color.White;
            stateProperties28.ForeColor = Color.Empty;
            stateProperties28.PlaceholderForeColor = Color.Empty;
            txtPassword.OnIdleState = stateProperties28;
            txtPassword.Padding = new Padding(3);
            txtPassword.PasswordChar = '*';
            txtPassword.PlaceholderForeColor = Color.Silver;
            txtPassword.PlaceholderText = "Password";
            txtPassword.ReadOnly = false;
            txtPassword.ScrollBars = ScrollBars.None;
            txtPassword.SelectedText = "";
            txtPassword.SelectionLength = 0;
            txtPassword.SelectionStart = 0;
            txtPassword.ShortcutsEnabled = true;
            txtPassword.Size = new Size(260, 39);
            txtPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtPassword.TabIndex = 2;
            txtPassword.TextAlign = HorizontalAlignment.Left;
            txtPassword.TextMarginBottom = 0;
            txtPassword.TextMarginLeft = 3;
            txtPassword.TextMarginTop = 1;
            txtPassword.TextPlaceholder = "Password";
            txtPassword.UseSystemPasswordChar = false;
            txtPassword.WordWrap = true;
            txtPassword.TextChange += txtPassword_TextChange;
            // 
            // btnLogin
            // 
            btnLogin.AllowAnimations = true;
            btnLogin.AllowMouseEffects = true;
            btnLogin.AllowToggling = false;
            btnLogin.Anchor = AnchorStyles.Top;
            btnLogin.AnimationSpeed = 200;
            btnLogin.AutoGenerateColors = false;
            btnLogin.AutoRoundBorders = false;
            btnLogin.AutoSizeLeftIcon = true;
            btnLogin.AutoSizeRightIcon = true;
            btnLogin.BackColor = Color.Transparent;
            btnLogin.BackColor1 = Color.FromArgb(51, 122, 183);
            btnLogin.BackgroundImage = (Image)resources.GetObject("btnLogin.BackgroundImage");
            btnLogin.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnLogin.ButtonText = "Login";
            btnLogin.ButtonTextMarginLeft = 0;
            btnLogin.ColorContrastOnClick = 45;
            btnLogin.ColorContrastOnHover = 45;
            btnLogin.Cursor = Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            btnLogin.CustomizableEdges = borderEdges4;
            btnLogin.DialogResult = DialogResult.None;
            btnLogin.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnLogin.DisabledFillColor = Color.Empty;
            btnLogin.DisabledForecolor = Color.Empty;
            btnLogin.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnLogin.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 162);
            btnLogin.ForeColor = Color.White;
            btnLogin.IconLeft = null;
            btnLogin.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnLogin.IconLeftCursor = Cursors.Default;
            btnLogin.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnLogin.IconMarginLeft = 11;
            btnLogin.IconPadding = 10;
            btnLogin.IconRight = null;
            btnLogin.IconRightAlign = ContentAlignment.MiddleRight;
            btnLogin.IconRightCursor = Cursors.Default;
            btnLogin.IconRightPadding = new Padding(3, 3, 7, 3);
            btnLogin.IconSize = 25;
            btnLogin.IdleBorderColor = Color.Empty;
            btnLogin.IdleBorderRadius = 0;
            btnLogin.IdleBorderThickness = 0;
            btnLogin.IdleFillColor = Color.Empty;
            btnLogin.IdleIconLeftImage = null;
            btnLogin.IdleIconRightImage = null;
            btnLogin.IndicateFocus = false;
            btnLogin.Location = new Point(50, 159);
            btnLogin.Name = "btnLogin";
            btnLogin.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnLogin.OnDisabledState.BorderRadius = 25;
            btnLogin.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnLogin.OnDisabledState.BorderThickness = 0;
            btnLogin.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnLogin.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnLogin.OnDisabledState.IconLeftImage = null;
            btnLogin.OnDisabledState.IconRightImage = null;
            btnLogin.onHoverState.BorderColor = Color.SeaGreen;
            btnLogin.onHoverState.BorderRadius = 25;
            btnLogin.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnLogin.onHoverState.BorderThickness = 0;
            btnLogin.onHoverState.FillColor = Color.SeaGreen;
            btnLogin.onHoverState.ForeColor = Color.Transparent;
            btnLogin.onHoverState.IconLeftImage = null;
            btnLogin.onHoverState.IconRightImage = null;
            btnLogin.OnIdleState.BorderColor = Color.MediumSeaGreen;
            btnLogin.OnIdleState.BorderRadius = 25;
            btnLogin.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnLogin.OnIdleState.BorderThickness = 0;
            btnLogin.OnIdleState.FillColor = Color.MediumSeaGreen;
            btnLogin.OnIdleState.ForeColor = Color.White;
            btnLogin.OnIdleState.IconLeftImage = null;
            btnLogin.OnIdleState.IconRightImage = null;
            btnLogin.OnPressedState.BorderColor = Color.Green;
            btnLogin.OnPressedState.BorderRadius = 25;
            btnLogin.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnLogin.OnPressedState.BorderThickness = 0;
            btnLogin.OnPressedState.FillColor = Color.Green;
            btnLogin.OnPressedState.ForeColor = Color.White;
            btnLogin.OnPressedState.IconLeftImage = null;
            btnLogin.OnPressedState.IconRightImage = null;
            btnLogin.Size = new Size(137, 35);
            btnLogin.TabIndex = 3;
            btnLogin.TextAlign = ContentAlignment.MiddleCenter;
            btnLogin.TextAlignment = HorizontalAlignment.Center;
            btnLogin.TextMarginLeft = 0;
            btnLogin.TextPadding = new Padding(0);
            btnLogin.UseDefaultRadiusAndThickness = true;
            btnLogin.Click += btnLogin_Click;
            // 
            // LoginRegisterForm
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(34, 35, 39);
            ClientSize = new Size(800, 450);
            Controls.Add(pnlLogin);
            Controls.Add(pnlReg);
            FormBorderStyle = FormBorderStyle.FixedSingle;
            Name = "LoginRegisterForm";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "LoginRegisterForm";
            Load += LoginRegisterForm_Load;
            pnlReg.ResumeLayout(false);
            bunifuShadowPanel2.ResumeLayout(false);
            bunifuShadowPanel2.PerformLayout();
            pnlLogin.ResumeLayout(false);
            bunifuShadowPanel1.ResumeLayout(false);
            bunifuShadowPanel1.PerformLayout();
            ResumeLayout(false);
        }

        #endregion

        //private Button btnRegister;
        //private TextBox txtRegEmail;
        //private TextBox txtRegUserName;
        //private TextBox textRegPw;
        private Panel pnlReg;
        //private Button btnToLogin;
        private Panel pnlLogin;
        //private Button btnToReg;
        private Label label2;
        private Label label1;
        private Label label7;
        private Label label6;
        private Label label5;
        private Label label3;
        private Label label4;
        private Bunifu.UI.WinForms.BunifuTextBox txtEmail;
        private Bunifu.UI.WinForms.BunifuTextBox txtPassword;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnLogin;
        private Bunifu.UI.WinForms.BunifuTextBox txtRegUserName;
        private Bunifu.UI.WinForms.BunifuTextBox txtRegFirstName;
        private Bunifu.UI.WinForms.BunifuTextBox txtRegPw;
        private Bunifu.UI.WinForms.BunifuTextBox txtRegLastName;
        private Bunifu.UI.WinForms.BunifuTextBox txtRegEmail;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnRegister;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnToReg;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnToLogin;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel1;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel2;
    }
}